opt_in_rules:
  - all
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_name
  - function_default_parameter_at_end
  - implicit_return
  - multiline_arguments
  - multiline_parameters
  - no_extension_access_modifier
  - no_grouping_extension
  - prefer_nimble
  - prohibited_interface_builder
  - required_deinit
  - strong_iboutlet
  - type_contents_order
  - vertical_whitespace_between_cases
  - vertical_whitespace_opening_braces
 
line_length: 120
